### ISSUE TITLE
[New Tip]: Use Matrix Parameter to Reduce Duplication

### ISSUE THREAD

**Issue by brivu** [CircleCI-Public/Config.Tips#29]
### What is the name of the config kind?

circleci.yaml

### Config Tip

```
version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:latest
  macos:
    macos:
      xcode: 14.2.0
  windows:
    machine:
      image: windows-server-2019-vs2019:stable

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: <<parameters.executor>>
    steps:
      - run: uname -a

workflows:
  test-deploy:
    jobs: 
      - build:
          name: test-build-on-<<matrix.executor>>
          matrix:
            parameters:
              executor: ["macos", "alpine", "windows" ]

```

### Give us a short description of the config kind

Run the same job with different inputs

### Body Area

In `CircleCI` the `matrix` parameter enables you to run the same jobs with different combinations of inputs. This helps reduce redundancy in your `config.yml`. 

For example, lets say you want to run a `build` job on three different `executors`: Windows, MacOS and Alpine Linux.
Your `config,yml` can look like the following: 

```
version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:latest
  macos:
    macos:
      xcode: 14.2.0
  windows:
    machine:
      image: windows-server-2019-vs2019:stable

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: <<parameters.executor>>
    steps:
      - run: uname -a

workflows:
  test-deploy:
    jobs: 
      - build:
          name: test-build-on-alpine
          executor: "alpine"
      - build:
          name: test-build-on-macos
          executor: "macos"
      - build:
          name: test-build-on-windows
          executor: "windows"
```

Notice how the `build` job is repeated three times in our `config` (once per executor).  The `matrix` parameter enables you to reference the `build` command once in your `config.yml`.
